POST http://localhost:3333/products
Content-Type: application/json

{
    "title"       : "Pneu de Carro",
    "brand"       : "Pireli",
    "category"    : "car"
}

###

GET http://localhost:3333/products

###
PUT http://localhost:3333/products/634fe74f-bbe3-44dc-8a72-f1a42a8b4bd5
Content-Type: application/json

{
    "title"       : "Pneu de mudo de novo",
    "brand"       : "Pirreli",
    "category"    : "car"
}

###

DELETE http://localhost:3333/products/e0a61d36-8ad2-42a4-9c34-e463c21d5992
